[package]
name = "fidelityfx-sys"
version = "0.1.0+probably-fsr3-3.0.4-or-ffx-1.1.x"
authors = ["Traverse Research <support@traverseresearch.nl>"]
edition = "2021"
license = "MIT"
homepage = "https://traverseresearch.nl"
repository = "https://github.com/Traverse-Research/fidelityfx-rs"
description = "AMD's FidelityFX SDK with low-level `sys` bindings"
include = [
  "src", # Recursively includes stuff from ./FidelityFX and its shader compiler source.  Those won't compile without including Vulkan-Headers or referencing it from VULKAN_SDK though
  "/LICENSE",
  "/FidelityFX/LICENSE.txt", # MIT
]
categories = ["rendering", "graphics", "external-ffi-bindings"] # https://crates.io/category_slugs
keywords = ["fidelityfx", "fsr", "upscaling", "vulkan", "d3d12"]
rust-version = "1.74"

[build-dependencies]
# Pin version to have control over how everything is generated (there is a CI
# check that validates that all files are generated as currently checked in):
bindgen = { version = "=0.69.5", optional = true }
cc = "1.0.83"
glob = "0.3"

[features]
vulkan = []
dx12 = []
generate-bindings = ["dep:bindgen"]
