[package]
name = "fidelityfx-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3"
widestring = "1.0"

[build-dependencies]
bindgen = { version = "0.69", optional = true }
cc = "1.0.83"
glob = "0.3"

[features]
vulkan = []
d3d12 = []
generate-bindings = ["dep:bindgen"]
