[package]
name = "api_gen"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# Pin version to have control over how everything is generated (there is a CI
# check that validates that all files are generated as currently checked in):
bindgen = "=0.72.1"
heck = "0.5"
