/* automatically generated by rust-bindgen 0.72.1 */

#[doc = " Resource allocation callback function."]
pub type PfnFfxResourceAllocatorFunc = ::std::option::Option<
    unsafe extern "C" fn(
        effectId: u32,
        initialState: D3D12_RESOURCE_STATES,
        pHeapProps: *const D3D12_HEAP_PROPERTIES,
        pD3DDesc: *const D3D12_RESOURCE_DESC,
        pFfxDesc: *const ResourceDescription,
        pOptimizedClear: *const D3D12_CLEAR_VALUE,
        ppD3DResource: *mut *mut ID3D12Resource,
    ) -> ReturnCode_t,
>;
#[doc = " Resource destruction callback function."]
pub type PfnFfxResourceDeallocatorFunc = ::std::option::Option<
    unsafe extern "C" fn(effectId: u32, pResource: *mut ID3D12Resource) -> ReturnCode_t,
>;
pub type PfnFfxHeapAllocatorFunc = ::std::option::Option<
    unsafe extern "C" fn(
        effectId: u32,
        pHeapDesc: *const D3D12_HEAP_DESC,
        aliasable: bool,
        ppD3DHeap: *mut *mut ID3D12Heap,
        pHeapStartOffset: *mut u64,
    ) -> ReturnCode_t,
>;
pub type PfnFfxHeapDeallocatorFunc = ::std::option::Option<
    unsafe extern "C" fn(
        effectId: u32,
        pD3DHeap: *mut ID3D12Heap,
        heapStartOffset: u64,
        heapSize: u64,
    ) -> ReturnCode_t,
>;
#[repr(C)]
pub struct CreateBackendDX12Desc {
    pub header: CreateContextDescHeader,
    #[doc = "< Device on which the backend will run."]
    pub device: *mut ID3D12Device,
}
#[repr(C)]
pub struct CreateBackendDX12AllocationCallbacksDesc {
    pub header: CreateContextDescHeader,
    #[doc = "< Resource allocation function (can be null)"]
    pub pfnFfxResourceAllocator: PfnFfxResourceAllocatorFunc,
    #[doc = "< Resource deallocation function (can be null)"]
    pub pfnFfxResourceDeallocator: PfnFfxResourceDeallocatorFunc,
    #[doc = "< Heap allocation function (can be null)"]
    pub pfnFfxHeapAllocator: PfnFfxHeapAllocatorFunc,
    #[doc = "< Heap deallocation function (can be null)"]
    pub pfnFfxHeapDeallocator: PfnFfxHeapDeallocatorFunc,
    #[doc = "< Constant buffer allocation function (can be null)"]
    pub pfnFfxConstantBufferAllocator: ConstantBufferAllocator,
}

pub const CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12: StructType_t =
    MAKE_BACKEND_SUB_ID(BACKEND_ID_DX12, 0x02);

pub const CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12_ALLOCATION_CALLBACKS: StructType_t =
    MAKE_BACKEND_SUB_ID(BACKEND_ID_DX12, 0x03);

unsafe impl TaggedStructure for CreateBackendDX12Desc {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CreateBackendDX12AllocationCallbacksDesc {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12_ALLOCATION_CALLBACKS;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}
