/* automatically generated by rust-bindgen 0.72.1 */

pub const FRAMEGENERATION_VERSION_MAJOR: u32 = 4;
pub const FRAMEGENERATION_VERSION_MINOR: u32 = 0;
pub const FRAMEGENERATION_VERSION_PATCH: u32 = 0;
impl CreateContextFramegenerationFlags {
    pub const ASYNC_WORKLOAD_SUPPORT: CreateContextFramegenerationFlags =
        CreateContextFramegenerationFlags(1);
    #[doc = "< A bit indicating if the motion vectors are rendered at display resolution."]
    pub const DISPLAY_RESOLUTION_MOTION_VECTORS: CreateContextFramegenerationFlags =
        CreateContextFramegenerationFlags(2);
    #[doc = "< A bit indicating that the motion vectors have the jittering pattern applied to them."]
    pub const MOTION_VECTORS_JITTER_CANCELLATION: CreateContextFramegenerationFlags =
        CreateContextFramegenerationFlags(4);
    #[doc = "< A bit indicating that the input depth buffer data provided is inverted [1..0]."]
    pub const DEPTH_INVERTED: CreateContextFramegenerationFlags =
        CreateContextFramegenerationFlags(8);
    #[doc = "< A bit indicating that the input depth buffer data provided is using an infinite far plane."]
    pub const DEPTH_INFINITE: CreateContextFramegenerationFlags =
        CreateContextFramegenerationFlags(16);
    #[doc = "< A bit indicating if the input color data provided to all inputs is using a high-dynamic range."]
    pub const HIGH_DYNAMIC_RANGE: CreateContextFramegenerationFlags =
        CreateContextFramegenerationFlags(32);
    #[doc = "< A bit indicating that the runtime should check some API values and report issues."]
    pub const DEBUG_CHECKING: CreateContextFramegenerationFlags =
        CreateContextFramegenerationFlags(64);
}
impl ::std::ops::BitOr<CreateContextFramegenerationFlags> for CreateContextFramegenerationFlags {
    type Output = Self;
    #[inline]
    fn bitor(self, other: Self) -> Self {
        CreateContextFramegenerationFlags(self.0 | other.0)
    }
}
impl ::std::ops::BitOrAssign for CreateContextFramegenerationFlags {
    #[inline]
    fn bitor_assign(&mut self, rhs: CreateContextFramegenerationFlags) {
        self.0 |= rhs.0;
    }
}
impl ::std::ops::BitAnd<CreateContextFramegenerationFlags> for CreateContextFramegenerationFlags {
    type Output = Self;
    #[inline]
    fn bitand(self, other: Self) -> Self {
        CreateContextFramegenerationFlags(self.0 & other.0)
    }
}
impl ::std::ops::BitAndAssign for CreateContextFramegenerationFlags {
    #[inline]
    fn bitand_assign(&mut self, rhs: CreateContextFramegenerationFlags) {
        self.0 &= rhs.0;
    }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct CreateContextFramegenerationFlags(pub ::std::os::raw::c_int);
impl DispatchFramegenerationFlags {
    #[doc = "< A bit indicating that the debug tear lines will be drawn to the generated output."]
    pub const DRAW_DEBUG_TEAR_LINES: DispatchFramegenerationFlags = DispatchFramegenerationFlags(1);
    #[doc = "< A bit indicating that the debug reset indicators will be drawn to the generated output."]
    pub const DRAW_DEBUG_RESET_INDICATORS: DispatchFramegenerationFlags =
        DispatchFramegenerationFlags(2);
    #[doc = "< A bit indicating that the generated output resource will contain debug views with relevant information."]
    pub const DRAW_DEBUG_VIEW: DispatchFramegenerationFlags = DispatchFramegenerationFlags(4);
    #[doc = "< A bit indicating that the context should only run frame interpolation and not modify the swapchain."]
    pub const NO_SWAPCHAIN_CONTEXT_NOTIFY: DispatchFramegenerationFlags =
        DispatchFramegenerationFlags(8);
    #[doc = "< A bit indicating that the debug pacing lines will be drawn to the generated output."]
    pub const DRAW_DEBUG_PACING_LINES: DispatchFramegenerationFlags =
        DispatchFramegenerationFlags(16);
    pub const RESERVED_1: DispatchFramegenerationFlags = DispatchFramegenerationFlags(32);
    pub const RESERVED_2: DispatchFramegenerationFlags = DispatchFramegenerationFlags(64);
}
impl ::std::ops::BitOr<DispatchFramegenerationFlags> for DispatchFramegenerationFlags {
    type Output = Self;
    #[inline]
    fn bitor(self, other: Self) -> Self {
        DispatchFramegenerationFlags(self.0 | other.0)
    }
}
impl ::std::ops::BitOrAssign for DispatchFramegenerationFlags {
    #[inline]
    fn bitor_assign(&mut self, rhs: DispatchFramegenerationFlags) {
        self.0 |= rhs.0;
    }
}
impl ::std::ops::BitAnd<DispatchFramegenerationFlags> for DispatchFramegenerationFlags {
    type Output = Self;
    #[inline]
    fn bitand(self, other: Self) -> Self {
        DispatchFramegenerationFlags(self.0 & other.0)
    }
}
impl ::std::ops::BitAndAssign for DispatchFramegenerationFlags {
    #[inline]
    fn bitand_assign(&mut self, rhs: DispatchFramegenerationFlags) {
        self.0 &= rhs.0;
    }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct DispatchFramegenerationFlags(pub ::std::os::raw::c_int);
impl UiCompositionFlags {
    #[doc = "< A bit indicating that we use premultiplied alpha for UI composition."]
    pub const USE_PREMUL_ALPHA: UiCompositionFlags = UiCompositionFlags(1);
    #[doc = "< A bit indicating that the swapchain should doublebuffer the UI resource."]
    pub const ENABLE_INTERNAL_UI_DOUBLE_BUFFERING: UiCompositionFlags = UiCompositionFlags(2);
}
impl ::std::ops::BitOr<UiCompositionFlags> for UiCompositionFlags {
    type Output = Self;
    #[inline]
    fn bitor(self, other: Self) -> Self {
        UiCompositionFlags(self.0 | other.0)
    }
}
impl ::std::ops::BitOrAssign for UiCompositionFlags {
    #[inline]
    fn bitor_assign(&mut self, rhs: UiCompositionFlags) {
        self.0 |= rhs.0;
    }
}
impl ::std::ops::BitAnd<UiCompositionFlags> for UiCompositionFlags {
    type Output = Self;
    #[inline]
    fn bitand(self, other: Self) -> Self {
        UiCompositionFlags(self.0 & other.0)
    }
}
impl ::std::ops::BitAndAssign for UiCompositionFlags {
    #[inline]
    fn bitand_assign(&mut self, rhs: UiCompositionFlags) {
        self.0 &= rhs.0;
    }
}
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct UiCompositionFlags(pub ::std::os::raw::c_int);
#[repr(C)]
pub struct CreateContextDescFrameGeneration {
    pub header: CreateContextDescHeader,
    #[doc = "< A combination of zero or more values from FfxApiCreateContextFramegenerationFlags."]
    pub flags: u32,
    #[doc = "< The resolution at which both rendered and generated frames will be displayed."]
    pub displaySize: Dimensions2D,
    #[doc = "< The maximum rendering resolution."]
    pub maxRenderSize: Dimensions2D,
    #[doc = "< The surface format for the backbuffer. One of the values from FfxApiSurfaceFormat."]
    pub backBufferFormat: u32,
}
#[repr(C)]
pub struct CallbackDescFrameGenerationPresent {
    pub header: DispatchDescHeader,
    #[doc = "< The device passed in (from a backend description) during context creation."]
    pub device: *mut ::std::os::raw::c_void,
    #[doc = "< A command list that will be executed before presentation."]
    pub commandList: *mut ::std::os::raw::c_void,
    #[doc = "< Backbuffer image either rendered or generated."]
    pub currentBackBuffer: Resource,
    #[doc = "< UI image for composition if passed. Otherwise empty."]
    pub currentUI: Resource,
    #[doc = "< Output image that will be presented."]
    pub outputSwapChainBuffer: Resource,
    #[doc = "< true if this frame is generated, false if rendered."]
    pub isGeneratedFrame: bool,
    #[doc = "< Identifier used to select internal resources when async support is enabled. Must increment by exactly one (1) for each frame. Any non-exactly-one difference will reset the frame generation logic."]
    pub frameID: u64,
}
#[repr(C)]
pub struct DispatchDescFrameGeneration {
    pub header: DispatchDescHeader,
    #[doc = "< The command list on which to register render commands."]
    pub commandList: *mut ::std::os::raw::c_void,
    #[doc = "< The current presentation color, this will be used as source data."]
    pub presentColor: Resource,
    #[doc = "< Destination targets (1 for each frame in numGeneratedFrames)."]
    pub outputs: [Resource; 4usize],
    #[doc = "< The number of frames to generate from the passed in color target."]
    pub numGeneratedFrames: u32,
    #[doc = "< A boolean value which when set to true, indicates the camera has moved discontinuously."]
    pub reset: bool,
    #[doc = "< The transfer function use to convert frame generation source color data to linear RGB. One of the values from FfxApiBackbufferTransferFunction."]
    pub backbufferTransferFunction: u32,
    #[doc = "< Min and max luminance values, used when converting HDR colors to linear RGB."]
    pub minMaxLuminance: [f32; 2usize],
    #[doc = "< The area of the backbuffer that should be used for generation in case only a part of the screen is used e.g. due to movie bars."]
    pub generationRect: Rect2D,
    #[doc = "< Identifier used to select internal resources when async support is enabled. Must increment by exactly one (1) for each frame. Any non-exactly-one difference will reset the frame generation logic."]
    pub frameID: u64,
}
pub type PresentCallbackFunc = ::std::option::Option<
    unsafe extern "C" fn(
        params: *mut CallbackDescFrameGenerationPresent,
        pUserCtx: *mut ::std::os::raw::c_void,
    ) -> ReturnCode_t,
>;
pub type FrameGenerationDispatchFunc = ::std::option::Option<
    unsafe extern "C" fn(
        params: *mut DispatchDescFrameGeneration,
        pUserCtx: *mut ::std::os::raw::c_void,
    ) -> ReturnCode_t,
>;
#[repr(C)]
pub struct ConfigureDescFrameGeneration {
    pub header: ConfigureDescHeader,
    #[doc = "< The swapchain to use with frame generation."]
    pub swapChain: *mut ::std::os::raw::c_void,
    #[doc = "< A UI composition callback to call when finalizing the frame image."]
    pub presentCallback: PresentCallbackFunc,
    #[doc = "< A pointer to be passed to the UI composition callback."]
    pub presentCallbackUserContext: *mut ::std::os::raw::c_void,
    #[doc = "< The frame generation callback to use to generate a frame."]
    pub frameGenerationCallback: FrameGenerationDispatchFunc,
    #[doc = "< A pointer to be passed to the frame generation callback."]
    pub frameGenerationCallbackUserContext: *mut ::std::os::raw::c_void,
    #[doc = "< Sets the state of frame generation. Set to false to disable frame generation."]
    pub frameGenerationEnabled: bool,
    #[doc = "< Sets the state of async workloads. Set to true to enable generation work on async compute."]
    pub allowAsyncWorkloads: bool,
    #[doc = "< The hudless back buffer image to use for UI extraction from backbuffer resource. May be empty."]
    pub HUDLessColor: Resource,
    #[doc = "< Zero or combination of flags from FfxApiDispatchFrameGenerationFlags."]
    pub flags: u32,
    #[doc = "< Set to true to only present generated frames."]
    pub onlyPresentGenerated: bool,
    #[doc = "< The area of the backbuffer that should be used for generation in case only a part of the screen is used e.g. due to movie bars"]
    pub generationRect: Rect2D,
    #[doc = "< Identifier used to select internal resources when async support is enabled. Must increment by exactly one (1) for each frame. Any non-exactly-one difference will reset the frame generation logic."]
    pub frameID: u64,
}
#[repr(C)]
pub struct DispatchDescFrameGenerationPrepare {
    pub header: DispatchDescHeader,
    #[doc = "< Identifier used to select internal resources when async support is enabled. Must increment by exactly one (1) for each frame. Any non-exactly-one difference will reset the frame generation logic."]
    pub frameID: u64,
    #[doc = "< Zero or combination of values from FfxApiDispatchFrameGenerationFlags."]
    pub flags: u32,
    #[doc = "< A command list to record frame generation commands into."]
    pub commandList: *mut ::std::os::raw::c_void,
    #[doc = "< The dimensions used to render game content, dilatedDepth, dilatedMotionVectors are expected to be of ths size."]
    pub renderSize: Dimensions2D,
    #[doc = "< The subpixel jitter offset applied to the camera."]
    pub jitterOffset: FloatCoords2D,
    #[doc = "< The scale factor to apply to motion vectors."]
    pub motionVectorScale: FloatCoords2D,
    #[doc = "< Time elapsed in milliseconds since the last frame."]
    pub frameTimeDelta: f32,
    #[doc = "< A (currently unused) boolean value which when set to true, indicates FrameGeneration will be called in reset mode"]
    pub unused_reset: bool,
    #[doc = "< The distance to the near plane of the camera."]
    pub cameraNear: f32,
    #[doc = "< The distance to the far plane of the camera. This is used only used in case of non infinite depth."]
    pub cameraFar: f32,
    #[doc = "< The camera angle field of view in the vertical direction (expressed in radians)."]
    pub cameraFovAngleVertical: f32,
    #[doc = "< The scale factor to convert view space units to meters"]
    pub viewSpaceToMetersFactor: f32,
    #[doc = "< The depth buffer data"]
    pub depth: Resource,
    #[doc = "< The motion vector data"]
    pub motionVectors: Resource,
}
#[repr(C)]
pub struct ConfigureDescFrameGenerationKeyValue {
    pub header: ConfigureDescHeader,
    #[doc = "< Configuration key, member of the FfxApiConfigureFrameGenerationKey enumeration."]
    pub key: u64,
    #[doc = "< Integer value or enum value to set."]
    pub u64_: u64,
    #[doc = "< Pointer to set or pointer to value to set."]
    pub ptr: *mut ::std::os::raw::c_void,
}
#[repr(i32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ConfigureFrameGenerationKey {
    #[doc = "< A key to set a debug view mode of display."]
    DEBUG_VIEW_MODE = 0,
    #[doc = "< A key to set a debug view scale for flow resources."]
    DEBUG_VIEW_FLOW_SCALE = 1,
}
#[repr(C)]
pub struct QueryDescFrameGenerationGetGPUMemoryUsage {
    pub header: QueryDescHeader,
    pub gpuMemoryUsageFrameGeneration: *mut EffectMemoryUsage,
}
#[repr(C)]
pub struct ConfigureDescFrameGenerationRegisterDistortionFieldResource {
    pub header: ConfigureDescHeader,
    #[doc = "< A resource containing distortion offset data. Needs to be 2-component (ie. RG). Read by FG shaders via Sample. Pixel value encodes [UV coordinate of pixel after lens distortion effect- UV coordinate of pixel before lens distortion]."]
    pub distortionField: Resource,
}
#[repr(C)]
pub struct CreateContextDescFrameGenerationHudless {
    pub header: CreateContextDescHeader,
    #[doc = "< The surface format for the hudless back buffer. One of the values from FfxApiSurfaceFormat."]
    pub hudlessBackBufferFormat: u32,
}
#[repr(C)]
pub struct DispatchDescFrameGenerationPrepareCameraInfo {
    pub header: ConfigureDescHeader,
    #[doc = "< The camera position in world space"]
    pub cameraPosition: [f32; 3usize],
    #[doc = "< The camera up normalized vector in world space."]
    pub cameraUp: [f32; 3usize],
    #[doc = "< The camera right normalized vector in world space."]
    pub cameraRight: [f32; 3usize],
    #[doc = "< The camera forward normalized vector in world space."]
    pub cameraForward: [f32; 3usize],
}
#[repr(C)]
pub struct QueryDescFrameGenerationGetGPUMemoryUsageV2 {
    pub header: QueryDescHeader,
    #[doc = "< For DX12: pointer to ID3D12Device. For VK, pointer to VkDevice. App needs to fill out before Query() call."]
    pub device: *mut ::std::os::raw::c_void,
    #[doc = "< App needs to fill out before Query() call."]
    pub maxRenderSize: Dimensions2D,
    #[doc = "< App needs to fill out before Query() call."]
    pub displaySize: Dimensions2D,
    #[doc = "< A combination of zero or more values from FfxApiCreateContextFramegenerationFlags."]
    pub createFlags: u32,
    #[doc = "< A combination of zero or more values from FfxApiDispatchFrameGenerationFlags."]
    pub dispatchFlags: u32,
    #[doc = "< The surface format for the backbuffer. One of the values from FfxApiSurfaceFormat. App needs to fill out before Query() call."]
    pub backBufferFormat: u32,
    #[doc = "< The surface format for HUDLessColor if used. Otherwise set value to FFX_API_SURFACE_FORMAT_UNKNOWN(0). App needs to fill out before Query() call."]
    pub hudlessBackBufferFormat: u32,
    #[doc = "< Output values by Query() call."]
    pub gpuMemoryUsageFrameGeneration: *mut EffectMemoryUsage,
}
#[repr(C)]
pub struct DispatchDescFrameGenerationPrepareV2 {
    pub header: DispatchDescHeader,
    #[doc = "< Identifier used to select internal resources when async support is enabled. Must increment by exactly one (1) for each frame. Any non-exactly-one difference will reset the frame generation logic."]
    pub frameID: u64,
    #[doc = "< Zero or combination of values from FfxApiDispatchFrameGenerationFlags."]
    pub flags: u32,
    #[doc = "< A command list to record frame generation commands into."]
    pub commandList: *mut ::std::os::raw::c_void,
    #[doc = "< The dimensions used to render game content, dilatedDepth, dilatedMotionVectors are expected to be of ths size."]
    pub renderSize: Dimensions2D,
    #[doc = "< The subpixel jitter offset applied to the camera."]
    pub jitterOffset: FloatCoords2D,
    #[doc = "< The scale factor to apply to motion vectors."]
    pub motionVectorScale: FloatCoords2D,
    #[doc = "< Time elapsed in milliseconds since the last frame."]
    pub frameTimeDelta: f32,
    #[doc = "< A boolean value which when set to true, indicates FrameGeneration will be called in reset mode"]
    pub reset: bool,
    #[doc = "< The distance to the near plane of the camera."]
    pub cameraNear: f32,
    #[doc = "< The distance to the far plane of the camera. This is used only used in case of non infinite depth."]
    pub cameraFar: f32,
    #[doc = "< The camera angle field of view in the vertical direction (expressed in radians)."]
    pub cameraFovAngleVertical: f32,
    #[doc = "< The scale factor to convert view space units to meters"]
    pub viewSpaceToMetersFactor: f32,
    #[doc = "< The depth buffer data"]
    pub depth: Resource,
    #[doc = "< The motion vector data"]
    pub motionVectors: Resource,
    #[doc = "< The camera position in world space"]
    pub cameraPosition: [f32; 3usize],
    #[doc = "< The camera up normalized vector in world space"]
    pub cameraUp: [f32; 3usize],
    #[doc = "< The camera right normalized vector in world space"]
    pub cameraRight: [f32; 3usize],
    #[doc = "< The camera forward normalized vector in world space"]
    pub cameraForward: [f32; 3usize],
}
#[repr(C)]
pub struct CallbackDescFrameGenerationPresentPremulAlpha {
    #[doc = "< Header for versioning & ABI stability"]
    pub header: Header,
    #[doc = "< Toggles whether UI gets premultiplied alpha blending or not"]
    pub usePremulAlpha: bool,
}
pub type WaitCallbackFunc = ::std::option::Option<
    unsafe extern "C" fn(fenceName: *mut u16, fenceValueToWaitFor: u64) -> i32,
>;
#[repr(C)]
pub struct CreateContextDescFrameGenerationVersion {
    pub header: CreateContextDescHeader,
    #[doc = "< The version of the API the application was built against. This must be set to FFX_FRAMEGENERATION_VERSION."]
    pub version: u32,
}
#[doc = " A structure representing the configuration options to pass to FrameInterpolationSwapChain\n\n @ingroup FfxInterface"]
#[repr(C)]
pub struct FrameGenerationConfig {
    #[doc = "< Header for versioning & ABI stability"]
    pub header: Header,
    #[doc = "< The <c><i>FfxSwapchain</i></c> to use with frame interpolation"]
    pub swapChain: *mut ::std::os::raw::c_void,
    #[doc = "< A UI composition callback to call when finalizing the frame image"]
    pub presentCallback: PresentCallbackFunc,
    #[doc = "< A pointer to be passed to the UI composition callback"]
    pub presentCallbackContext: *mut ::std::os::raw::c_void,
    #[doc = "< The frame generation callback to use to generate the interpolated frame"]
    pub frameGenerationCallback: FrameGenerationDispatchFunc,
    #[doc = "< A pointer to be passed to the frame generation callback"]
    pub frameGenerationCallbackContext: *mut ::std::os::raw::c_void,
    #[doc = "< Sets the state of frame generation. Set to false to disable frame generation"]
    pub frameGenerationEnabled: bool,
    #[doc = "< Sets the state of async workloads. Set to true to enable interpolation work on async compute"]
    pub allowAsyncWorkloads: bool,
    #[doc = "< Sets the state of async presentation (console only). Set to true to enable present from async command queue"]
    pub allowAsyncPresent: bool,
    #[doc = "< The hudless back buffer image to use for UI extraction from backbuffer resource"]
    pub HUDLessColor: Resource,
    #[doc = "< Flags"]
    pub flags: u32,
    #[doc = "< Set to true to only present interpolated frame"]
    pub onlyPresentInterpolated: bool,
    #[doc = "< Set the area in the backbuffer that will be interpolated"]
    pub interpolationRect: Rect2D,
    #[doc = "< A frame identifier used to synchronize resource usage in workloads"]
    pub frameID: u64,
    #[doc = "< Sets the state of pacing debug lines. Set to true to display debug lines"]
    pub drawDebugPacingLines: bool,
}
impl Default for FrameGenerationConfig {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}

unsafe impl TaggedStructure for CreateContextDescFrameGeneration {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATION;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CallbackDescFrameGenerationPresent {
    const TAG: StructType_t = CALLBACK_DESC_TYPE_FRAMEGENERATION_PRESENT;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for DispatchDescFrameGeneration {
    const TAG: StructType_t = DISPATCH_DESC_TYPE_FRAMEGENERATION;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for ConfigureDescFrameGeneration {
    const TAG: StructType_t = CONFIGURE_DESC_TYPE_FRAMEGENERATION;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for DispatchDescFrameGenerationPrepare {
    const TAG: StructType_t = DISPATCH_DESC_TYPE_FRAMEGENERATION_PREPARE;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for ConfigureDescFrameGenerationKeyValue {
    const TAG: StructType_t = CONFIGURE_DESC_TYPE_FRAMEGENERATION_KEYVALUE;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for QueryDescFrameGenerationGetGPUMemoryUsage {
    const TAG: StructType_t = QUERY_DESC_TYPE_FRAMEGENERATION_GPU_MEMORY_USAGE;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for ConfigureDescFrameGenerationRegisterDistortionFieldResource {
    const TAG: StructType_t = CONFIGURE_DESC_TYPE_FRAMEGENERATION_REGISTERDISTORTIONRESOURCE;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CreateContextDescFrameGenerationHudless {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATION_HUDLESS;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for DispatchDescFrameGenerationPrepareCameraInfo {
    const TAG: StructType_t = DISPATCH_DESC_TYPE_FRAMEGENERATION_PREPARE_CAMERAINFO;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for QueryDescFrameGenerationGetGPUMemoryUsageV2 {
    const TAG: StructType_t = QUERY_DESC_TYPE_FRAMEGENERATION_GPU_MEMORY_USAGE_V2;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for DispatchDescFrameGenerationPrepareV2 {
    const TAG: StructType_t = DISPATCH_DESC_TYPE_FRAMEGENERATION_PREPARE_V2;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CallbackDescFrameGenerationPresentPremulAlpha {
    const TAG: StructType_t = CALLBACK_DESC_TYPE_FRAMEGENERATION_PRESENT_PREMUL_ALPHA;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CreateContextDescFrameGenerationVersion {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATION_VERSION;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}
