/* automatically generated by rust-bindgen 0.72.1 */

pub const FRAMEGENERATION_SWAPCHAIN_DX12_VERSION_MAJOR: u32 = 3;
pub const FRAMEGENERATION_SWAPCHAIN_DX12_VERSION_MINOR: u32 = 1;
pub const FRAMEGENERATION_SWAPCHAIN_DX12_VERSION_PATCH: u32 = 6;
#[repr(C)]
pub struct CreateContextDescFrameGenerationSwapChainWrapDX12 {
    pub header: CreateContextDescHeader,
    #[doc = "< Input swap chain to wrap, output frame interpolation swapchain."]
    pub swapchain: *mut *mut IDXGISwapChain4,
    #[doc = "< Input command queue to be used for presentation."]
    pub gameQueue: *mut ID3D12CommandQueue,
}
#[repr(C)]
pub struct CreateContextDescFrameGenerationSwapChainNewDX12 {
    pub header: CreateContextDescHeader,
    #[doc = "< Output frame interpolation swapchain."]
    pub swapchain: *mut *mut IDXGISwapChain4,
    #[doc = "< Swap chain creation parameters."]
    pub desc: *mut DXGI_SWAP_CHAIN_DESC,
    #[doc = "< IDXGIFactory to use for DX12 swapchain creation."]
    pub dxgiFactory: *mut IDXGIFactory,
    #[doc = "< Input command queue to be used for presentation."]
    pub gameQueue: *mut ID3D12CommandQueue,
}
#[repr(C)]
pub struct CreateContextDescFrameGenerationSwapChainForHwndDX12 {
    pub header: CreateContextDescHeader,
    #[doc = "< Output frame interpolation swapchain."]
    pub swapchain: *mut *mut IDXGISwapChain4,
    #[doc = "< HWND handle for the calling application;"]
    pub hwnd: HWND,
    #[doc = "< Swap chain creation parameters."]
    pub desc: *mut DXGI_SWAP_CHAIN_DESC1,
    #[doc = "< Fullscreen swap chain creation parameters."]
    pub fullscreenDesc: *mut DXGI_SWAP_CHAIN_FULLSCREEN_DESC,
    #[doc = "< IDXGIFactory to use for DX12 swapchain creation."]
    pub dxgiFactory: *mut IDXGIFactory,
    #[doc = "< Input command queue to be used for presentation."]
    pub gameQueue: *mut ID3D12CommandQueue,
}
#[repr(C)]
pub struct ConfigureDescFrameGenerationSwapChainRegisterUiResourceDX12 {
    pub header: ConfigureDescHeader,
    #[doc = "< Resource containing user interface for composition. May be empty."]
    pub uiResource: Resource,
    #[doc = "< Zero or combination of values from FfxApiUiCompositionFlags."]
    pub flags: u32,
}
#[repr(C)]
pub struct QueryDescFrameGenerationSwapChainInterpolationCommandListDX12 {
    pub header: QueryDescHeader,
    #[doc = "< Output command list (ID3D12GraphicsCommandList) to be used for frame generation dispatch."]
    pub pOutCommandList: *mut *mut ::std::os::raw::c_void,
}
#[repr(C)]
pub struct QueryDescFrameGenerationSwapChainInterpolationTextureDX12 {
    pub header: QueryDescHeader,
    #[doc = "< Output resource in which the frame interpolation result should be placed."]
    pub pOutTexture: *mut Resource,
}
#[repr(C)]
pub struct DispatchDescFrameGenerationSwapChainWaitForPresentsDX12 {
    pub header: DispatchDescHeader,
}
#[repr(C)]
pub struct ConfigureDescFrameGenerationSwapChainKeyValueDX12 {
    pub header: ConfigureDescHeader,
    #[doc = "< Configuration key, member of the FfxApiConfigureFrameGenerationSwapChainKeyDX12 enumeration."]
    pub key: u64,
    #[doc = "< Integer value or enum value to set."]
    pub u64_: u64,
    #[doc = "< Pointer to set or pointer to value to set."]
    pub ptr: *mut ::std::os::raw::c_void,
}
#[repr(i32)]
#[non_exhaustive]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ConfigureFrameGenerationSwapChainKeyDX12 {
    #[doc = "< Sets FfxWaitCallbackFunc"]
    WAITCALLBACK = 0,
    #[doc = "< Sets FfxApiSwapchainFramePacingTuning"]
    FRAMEPACINGTUNING = 2,
}
#[repr(C)]
pub struct QueryFrameGenerationSwapChainGetGPUMemoryUsageDX12 {
    pub header: QueryDescHeader,
    pub gpuMemoryUsageFrameGenerationSwapchain: *mut EffectMemoryUsage,
}
#[repr(C)]
pub struct QueryFrameGenerationSwapChainGetGPUMemoryUsageDX12V2 {
    pub header: QueryDescHeader,
    #[doc = "< For DX12: pointer to ID3D12Device. App needs to fill out before Query() call."]
    pub device: *mut ::std::os::raw::c_void,
    #[doc = "< App needs to fill out before Query() call."]
    pub displaySize: Dimensions2D,
    #[doc = "< The surface format for the backbuffer. One of the values from FfxApiSurfaceFormat. App needs to fill out before Query() call."]
    pub backBufferFormat: u32,
    #[doc = "< The number of backbuffers in the swapchain. App needs to fill out before Query() call."]
    pub backBufferCount: u32,
    #[doc = "< This is the resolution of the resource that will be used for UI composition. Set to (0,0) if providing null uiResource in  ffxConfigureDescFrameGenerationSwapChainRegisterUiResourceDX12. App needs to fill out before Query() call."]
    pub uiResourceSize: Dimensions2D,
    #[doc = "< The surface format for the uiResource. One of the values from FfxApiSurfaceFormat. Set to FFX_API_SURFACE_FORMAT_UNKNOWN(0) if providing null uiResource in  ffxConfigureDescFrameGenerationSwapChainRegisterUiResourceDX12. App needs to fill out before Query() call."]
    pub uiResourceFormat: u32,
    #[doc = "< Zero or combination of values from FfxApiUiCompositionFlags. App needs to fill out before Query() call."]
    pub flags: u32,
    pub gpuMemoryUsageFrameGenerationSwapchain: *mut EffectMemoryUsage,
}
#[repr(C)]
pub struct CreateContextDescFrameGenerationSwapChainVersionDX12 {
    pub header: CreateContextDescHeader,
    #[doc = "< The version of the API the application was built against. This must be set to FFX_FRAMEGENERATION_SWAPCHAIN_DX12_VERSION."]
    pub version: u32,
}

pub const CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12: StructType_t =
    MAKE_BACKEND_SUB_ID(BACKEND_ID_DX12, 0x02);

pub const CREATE_CONTEXT_DESC_TYPE_BACKEND_DX12_ALLOCATION_CALLBACKS: StructType_t =
    MAKE_BACKEND_SUB_ID(BACKEND_ID_DX12, 0x03);

pub const fn FRAMEGENERATION_SWAPCHAIN_DX12_MAKE_VERSION(
    major: u32,
    minor: u32,
    patch: u32,
) -> u32 {
    ((major) << 22) | ((minor) << 12) | (patch)
}

pub const FRAMEGENERATION_SWAPCHAIN_DX12_VERSION: u32 = FRAMEGENERATION_SWAPCHAIN_DX12_MAKE_VERSION(
    FRAMEGENERATION_SWAPCHAIN_DX12_VERSION_MAJOR,
    FRAMEGENERATION_SWAPCHAIN_DX12_VERSION_MINOR,
    FRAMEGENERATION_SWAPCHAIN_DX12_VERSION_PATCH,
);

pub const CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_WRAP_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x01);

pub const CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_NEW_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x05);

pub const CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_FOR_HWND_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x06);

pub const CONFIGURE_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_REGISTERUIRESOURCE_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x02);

pub const QUERY_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_INTERPOLATIONCOMMANDLIST_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x03);

pub const QUERY_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_INTERPOLATIONTEXTURE_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x04);

pub const DISPATCH_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_WAIT_FOR_PRESENTS_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x07);

pub const CONFIGURE_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_KEYVALUE_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x08);

pub const QUERY_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_GPU_MEMORY_USAGE_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x09);

pub const QUERY_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_GPU_MEMORY_USAGE_DX12_V2: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x0a);

pub const CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_VERSION_DX12: StructType_t =
    MAKE_BACKEND_EFFECT_SUB_ID(BACKEND_ID_DX12, EFFECT_ID_FRAMEGENERATIONSWAPCHAIN, 0x0b);

unsafe impl TaggedStructure for CreateContextDescFrameGenerationSwapChainWrapDX12 {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_WRAP_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CreateContextDescFrameGenerationSwapChainNewDX12 {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_NEW_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CreateContextDescFrameGenerationSwapChainForHwndDX12 {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_FOR_HWND_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for ConfigureDescFrameGenerationSwapChainRegisterUiResourceDX12 {
    const TAG: StructType_t = CONFIGURE_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_REGISTERUIRESOURCE_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for QueryDescFrameGenerationSwapChainInterpolationCommandListDX12 {
    const TAG: StructType_t =
        QUERY_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_INTERPOLATIONCOMMANDLIST_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for QueryDescFrameGenerationSwapChainInterpolationTextureDX12 {
    const TAG: StructType_t = QUERY_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_INTERPOLATIONTEXTURE_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for DispatchDescFrameGenerationSwapChainWaitForPresentsDX12 {
    const TAG: StructType_t = DISPATCH_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_WAIT_FOR_PRESENTS_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for ConfigureDescFrameGenerationSwapChainKeyValueDX12 {
    const TAG: StructType_t = CONFIGURE_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_KEYVALUE_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}

unsafe impl TaggedStructure for CreateContextDescFrameGenerationSwapChainVersionDX12 {
    const TAG: StructType_t = CREATE_CONTEXT_DESC_TYPE_FRAMEGENERATIONSWAPCHAIN_VERSION_DX12;
    fn header(&self) -> &Header {
        &self.header
    }
    fn header_mut(&mut self) -> &mut Header {
        &mut self.header
    }
}
